In [6]:
import pandas as pd
from pathlib import Path
sales_csv_path = Path('../Data/sales_data.csv')
menu_csv_path = Path('../Data/menu_data.csv')
sales_df = pd.read_csv(sales_csv_path)
menu_df = pd.read_csv(menu_csv_path)

sales_df['Date'] = pd.to_datetime(sales_df['Date'])
sales_df['Customer_Id'] = 0
count = 1
list_of_customer_numbers = {}

for credit_card_number in sales_df['Credit_Card_Number']:
    if credit_card_number in list_of_customer_numbers:
        pass
    else:
        list_of_customer_numbers[credit_card_number] = count
        count+=1
        
for index, row in sales_df.iterrows():
    if row[2] in list_of_customer_numbers.keys():
        sales_df.iloc[index,5] = list_of_customer_numbers[row[2]]
        

        
menu_df.set_index('item', inplace = True)
sales_df.set_index('Menu_Item', inplace = True)


combined_df = sales_df.join(menu_df)
combined_df.reset_index(inplace = True)
combined_df.rename(columns = {'index': "Item_Ordered", 'price': 'Price', 'cost': 'Cost'}, inplace = True)
combined_df.drop(columns = ['Credit_Card_Number', 'description', 'category'], inplace = True)
combined_df['Revenue'] = (combined_df['Quantity']*combined_df['Price'])-combined_df['Cost']

In [9]:
combined_df.sort_values('Line_Item_ID', inplace = True)
combined_df.set_index('Line_Item_ID', inplace = True)

In [10]:
combined_df

,Item_Ordered,Date,Quantity,Customer_Id,Price,Cost,Revenue
Line_Item_ID,,,,,,,
1,spicy miso ramen,2017-01-01,1,1001,12.0,5,7.0
2,spicy miso ramen,2017-01-01,1,1001,12.0,5,7.0
3,tori paitan ramen,2017-01-01,3,1002,13.0,6,33.0
4,tori paitan ramen,2017-01-01,3,1002,13.0,6,33.0
5,truffle butter ramen,2017-01-01,1,1003,14.0,7,7.0
...,...,...,...,...,...,...,...
74120,tonkotsu ramen,2018-12-31,4,38060,13.0,6,46.0
74121,vegetarian spicy miso,2018-12-31,1,38061,12.0,5,7.0
74122,vegetarian spicy miso,2018-12-31,1,38061,12.0,5,7.0
74123,spicy miso ramen,2018-12-31,2,38062,12.0,5,19.0
74124,spicy miso ramen,2018-12-31,2,38062,12.0,5,19.0

In [28]:
cookies = []
for index, row in combined_df.iterrows():
    if row['Item_Ordered'] == 'spicy miso ramen':
        cookies.append(combined_df.iloc[index,5])
        break

In [35]:
spicy_miso_ramen_quantity = []
spicy_miso_ramen_price = []
spicy_miso_ramen_cost = []
spicy_miso_ramen_cutomer_id = []
spicy_miso_ramen_date = []
spicy_miso_ramen_revenue = []   

tori_paitan_ramen_quantity = []
tori_paitan_ramen_price = []
tori_paitan_ramen_cost = []
tori_paitan_ramen_cutomer_id = []
tori_paitan_ramen_date = []
tori_paitan_ramen_revenue = []  

truffle_butter_ramen_quantity = []
truffle_butter_ramen_price = []
truffle_butter_ramen_cost = []
truffle_butter_ramen_cutomer_id = []
truffle_butter_ramen_date = []
truffle_butter_ramen_revenue = []  

tonkotsu_ramen_quantity = []
tonkotsu_ramen_price = []
tonkotsu_ramen_cost = []
tonkotsu_ramen_cutomer_id = []
tonkotsu_ramen_date = []
tonkotsu_ramen_revenue = []  

vegetarian_spicy_miso_quantity = []
vegetarian_spicy_miso_price = []
vegetarian_spicy_miso_cost = []
vegetarian_spicy_miso_cutomer_id = []
vegetarian_spicy_miso_date = []
vegetarian_spicy_miso_revenue = []  

shio_ramen_quantity = []
shio_ramen_price = []
shio_ramen_cost = []
shio_ramen_cutomer_id = []
shio_ramen_date = []
shio_ramen_revenue = []  

miso_crab_ramen_quantity = []
miso_crab_ramen_price = []
miso_crab_ramen_cost = []
miso_crab_ramen_cutomer_id = []
miso_crab_ramen_date = []
miso_crab_ramen_revenue = []  

nagomi_shoyu_quantity = []
nagomi_shoyu_price = []
nagomi_shoyu_cost = []
nagomi_shoyu_cutomer_id = []
nagomi_shoyu_date = []
nagomi_shoyu_revenue = []  

soft_shell_miso_crab_ramen_quantity = []
soft_shell_miso_crab_ramen_price = []
soft_shell_miso_crab_ramen_cost = []
soft_shell_miso_crab_ramen_cutomer_id = []
soft_shell_miso_crab_ramen_date = []
soft_shell_miso_crab_ramen_revenue = []  

burnt_garlic_tonkotsu_ramen_quantity = []
burnt_garlic_tonkotsu_ramen_price = []
burnt_garlic_tonkotsu_ramen_cost = []
burnt_garlic_tonkotsu_ramen_cutomer_id = []
burnt_garlic_tonkotsu_ramen_date = []
burnt_garlic_tonkotsu_ramen_revenue = []  

vegetarian_curry_king_trumpet_mushroom_ramen_quantity = []
vegetarian_curry_king_trumpet_mushroom_ramen_price = []
vegetarian_curry_king_trumpet_mushroom_ramen_cost = []
vegetarian_curry_king_trumpet_mushroom_ramen_cutomer_id = []
vegetarian_curry_king_trumpet_mushroom_ramen_date = []
vegetarian_curry_king_trumpet_mushroom_ramen_revenue = []

In [33]:
for index, row in combined_df.iterrows():
    if row['Item_Ordered'] == 'spicy miso ramen':
        spicy_miso_ramen_quantity.append(combined_df.iloc[index,2])
        spicy_miso_ramen_price.append(combined_df.iloc[index,4])
        spicy_miso_ramen_cost.append(combined_df.iloc[index,5])
        spicy_miso_ramen_cutomer_id.append(combined_df.iloc[index,3])
        spicy_miso_ramen_date.append(combined_df.iloc[index,1])
        spicy_miso_ramen_revenue.append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] == 'tori paitan ramen':
#         tori_paitan_ramen_quantity.append(combined_df.iloc[index,2].values)
#         tori_paitan_ramen_price.append(combined_df.iloc[index,4].values)
#         tori_paitan_ramen_cost.append(combined_df.iloc[index,5].values)
#         tori_paitan_ramen_cutomer_id.append(combined_df.iloc[index,3].values)
#         tori_paitan_ramen_date.append(combined_df.iloc[index,1].values)
#         tori_paitan_ramen_revenue.append(combined_df.iloc[index,6].values)
#     elif row['Item_Ordered'] == 'truffle butter ramen':
#         truffle_butter_ramen_quantity.append(combined_df.iloc[index,2].values)
#         truffle_butter_ramen_price.append(combined_df.iloc[index,4].values)
#         truffle_butter_ramen_cost.append(combined_df.iloc[index,5].values)
#         truffle_butter_ramen_cutomer_id.append(combined_df.iloc[index,3])
#         truffle_butter_ramen_date.append(combined_df.iloc[index,1])
#         truffle_butter_ramen_revenue.append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] == 'tonkotsu ramen':
#         tonkotsu_ramen_quantity.append(combined_df.iloc[index,2])
#         tonkotsu_ramen_price.append(combined_df.iloc[index,4])
#         tonkotsu_ramen_cost.append(combined_df.iloc[index,5])
#         tonkotsu_ramen_cutomer_id.append(combined_df.iloc[index,3])
#         tonkotsu_ramen_date.append(combined_df.iloc[index,1])
#         tonkotsu_ramen_revenue.append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] ==  'vegetarian spicy miso':
#         vegetarian_spicy_miso_quantity.append(combined_df.iloc[index,2])
#         vegetarian_spicy_miso_price.append(combined_df.iloc[index,4])
#         vegetarian_spicy_miso_cost.append(combined_df.iloc[index,5])
#         vegetarian_spicy_miso_cutomer_id.append(combined_df.iloc[index,3])
#         vegetarian_spicy_miso_date.append(combined_df.iloc[index,1])
#         vegetarian_spicy_miso_revenue.append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] == 'shio ramen':
#         shio_ramen_quantity.append(combined_df.iloc[index,2])
#         shio_ramen_price.append(combined_df.iloc[index,4])
#         shio_ramen_cost.append(combined_df.iloc[index,5])
#         shio_ramen_cutomer_id.append(combined_df.iloc[index,3])
#         shio_ramen_date.append(combined_df.iloc[index,1])
#         shio_ramen_revenue .append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] == 'miso crab ramen':
#         miso_crab_ramen_quantity.append(combined_df.iloc[index,2])
#         miso_crab_ramen_price.append(combined_df.iloc[index,4])
#         miso_crab_ramen_cost.append(combined_df.iloc[index,5])
#         miso_crab_ramen_cutomer_id.append(combined_df.iloc[index,3])
#         miso_crab_ramen_date.append(combined_df.iloc[index,1])
#         miso_crab_ramen_revenue.append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] == 'nagomi shoyu':
#         nagomi_shoyu_quantity.append(combined_df.iloc[index,2])
#         nagomi_shoyu_price.append(combined_df.iloc[index,4])
#         nagomi_shoyu_cost.append(combined_df.iloc[index,5])
#         nagomi_shoyu_cutomer_id.append(combined_df.iloc[index,3])
#         nagomi_shoyu_date.append(combined_df.iloc[index,1])
#         nagomi_shoyu_revenue.append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] == 'soft-shell miso crab ramen':
#         soft_shell_miso_crab_ramen_quantity.append(combined_df.iloc[index,2])
#         soft_shell_miso_crab_ramen_price.append(combined_df.iloc[index,4])
#         soft_shell_miso_crab_ramen_cost.append(combined_df.iloc[index,5])
#         soft_shell_miso_crab_ramen_cutomer_id.append(combined_df.iloc[index,3])
#         soft_shell_miso_crab_ramen_date.append(combined_df.iloc[index,1])
#         soft_shell_miso_crab_ramen_revenue.append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] == 'burnt garlic tonkotsu ramen':
#         burnt_garlic_tonkotsu_ramen_quantity.append(combined_df.iloc[index,2])
#         burnt_garlic_tonkotsu_ramen_price.append(combined_df.iloc[index,4])
#         burnt_garlic_tonkotsu_ramen_cost.append(combined_df.iloc[index,5])
#         burnt_garlic_tonkotsu_ramen_cutomer_id.append(combined_df.iloc[index,3])
#         burnt_garlic_tonkotsu_ramen_date.append(combined_df.iloc[index,1])
#         burnt_garlic_tonkotsu_ramen_revenue.append(combined_df.iloc[index,6])
#     elif row['Item_Ordered'] == 'vegetarian curry + king trumpet mushroom ramen':
#         vegetarian_curry_king_trumpet_mushroom_ramen_quantity.append(combined_df.iloc[index,2])
#         vegetarian_curry_king_trumpet_mushroom_ramen_price.append(combined_df.iloc[index,4])
#         vegetarian_curry_king_trumpet_mushroom_ramen_cost.append(combined_df.iloc[index,5])
#         vegetarian_curry_king_trumpet_mushroom_ramen_cutomer_id.append(combined_df.iloc[index,3])
#         vegetarian_curry_king_trumpet_mushroom_ramen_date.append(combined_df.iloc[index,1])
#         vegetarian_curry_king_trumpet_mushroom_ramen_revenue.append(combined_df.iloc[index,6])
#     else:
#         print('You made an error')
#         print(index)

IndexError: single positional indexer is out-of-bounds

In [15]:
list_of_menu_items = []
for item in combined_df['Item_Ordered']:
    if item in list_of_menu_items:
        pass
    else:
        list_of_menu_items.append(item)

In [36]:
spicy_miso_ramen_quantity

[]

In [19]:
len(list_of_menu_items)

11

In [23]:
asdfadsf = []

In [25]:
asdfadsf.append(3)

In [26]:
asdfadsf

[3]